main:mycat openfile
mycat:../../include/common.h ../../util/common.cc mycat.cc
	g++ -o mycat -I../../include ../../util/common.cc mycat.cc
openfile:../../include/common.h ../../util/common.cc openfile.cc
	g++ -o openfile -I../../include ../../util/common.cc openfile.cc
