main:tcp udp 
tcp:../include/common.h ../util/common.cc tcp.cc
	g++ -o tcp -I../include ../util/common.cc tcp.cc
udp:../include/common.h ../util/common.cc udp.cc
	g++ -o udp -I../include ../util/common.cc udp.cc
