main:tcp udp udp_conn 
tcp:../include/common.h ../util/common.cc tcp.cc
	g++ -o tcp -I../include ../util/common.cc tcp.cc
udp:../include/common.h ../util/common.cc udp.cc
	g++ -o udp -I../include ../util/common.cc udp.cc
udp_conn:../include/common.h ../util/common.cc udp_conn.cc
	g++ -o udp_conn -I../include ../util/common.cc udp_conn.cc
