main:ancillary bindaddr echo_datagram echo_stream passdescriptor sockpair cred
	$(MAKE) -C./ancillary 
	$(MAKE) -C./bindaddr 
	$(MAKE) -C./echo_datagram 
	$(MAKE) -C./echo_stream 
	$(MAKE) -C./passdescriptor 
	$(MAKE) -C./sockpair
	$(MAKE) -C./cred
