main:if_nameindex if_nametoindex if_indextoname getdevinfo

if_nameindex:if_nameindex.cc
	gcc -o if_nameindex if_nameindex.cc
if_nametoindex:if_nametoindex.cc
	gcc -o if_nametoindex if_nametoindex.cc
if_indextoname:if_indextoname.cc
	gcc -o if_indextoname if_indextoname.cc
getdevinfo:getdevinfo.cc
	gcc -o getdevinfo getdevinfo.cc
