main:icmp myping
icmp:../../include/common.h ../../util/common.cc ./icmp.cc
	g++ -g -o icmp -I../../include ../../util/common.cc ./icmp.cc
myping:../../include/common.h ../../util/common.cc ./myping.cc
	g++ -g -o myping -I../../include ../../util/common.cc ./myping.cc
