main:echo attack
echo:../../include/common.h ../../util/common.cc echo.cc
	g++ -o echo -I../../include ../../util/common.cc echo.cc
attack:../../include/common.h ../../util/common.cc attack.cc
	g++ -o attack -I../../include ../../util/common.cc attack.cc
