main:concurrent_test echo options echo_udp advcio template advcio unixdomainprotocols
	$(MAKE) -C./concurrent_test
	$(MAKE) -C./echo
	$(MAKE) -C./options
	$(MAKE) -C./echo_udp
	$(MAKE) -C./template
	$(MAKE) -C./advcio
	$(MAKE) -C./unixdomainprotocols

