main:basic\
	concurrent_server\
	exception_accept\
	exception_sigpipe\
	multiplexing_epoll_server\
	multiplexing_poll_server\
	multiplexing_select_client\
	multiplexing_select_client_nobuffer\
	multiplexing_select_client_shutdown\
	multiplexing_select_server\
	processzombie
	$(MAKE) -C./concurrent_server
	$(MAKE) -C./exception_accept
	$(MAKE) -C./exception_sigpipe
	$(MAKE) -C./multiplexing_epoll_server
	$(MAKE) -C./multiplexing_poll_server
	$(MAKE) -C./multiplexing_select_client
	$(MAKE) -C./multiplexing_select_client_nobuffer
	$(MAKE) -C./multiplexing_select_client_shutdown
	$(MAKE) -C./multiplexing_select_server
