main:showopts_v1 showopts_v2
showopts_v1:../../include/common.h ../../util/common.cc ../../util/showopts.cc showopts_v1.cc
	g++ -o showopts_v1 -I../../include ../../util/common.cc ../../util/showopts.cc showopts_v1.cc
showopts_v2:../../include/common.h ../../util/common.cc ../../util/showopts.cc showopts_v2.cc
	g++ -o showopts_v2 -I../../include ../../util/common.cc ../../util/showopts.cc showopts_v2.cc
