target:main upper
upper:../../include/common.h ../../util/common.cc upper.cc
	g++ -g -o upper -I../../include ../../util/common.cc upper.cc
main:../../include/common.h ../../util/common.cc main.cc
	g++ -g -o main -I../../include ../../util/common.cc main.cc
